version: "3.1"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    expose:
      - "8080"
    env_file:
      - .env
    ports:
      - "127.0.0.1:8080:8080"
    container_name: eduhelper-bot
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${DB_URL}
      - TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_BOT_PATH=${TELEGRAM_BOT_PATH}
  db:
    image: "postgres:16"
    container_name: eduhelper-db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=eduhelper-bot
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
